### ISSUE TITLE
加了插件但是进服还是没有加载自己的材质包，只加载了服务器资源包

### ISSUE THREAD

**Issue by yufengya0420** [ZGDD-BE/LLSE-Plugins#1]
加了插件但是进服还是没有加载自己的材质包，只加载了服务器资源包

**Comment by yufengya0420** [comment]
dll版本正常，js版本失效

**Comment by yufengya0420** [comment]
ll2.15.0，bds1.20.11

**Comment by dofes** [comment]
> 加了插件但是进服还是没有加载自己的材质包，只加载了服务器资源包

你确定?我自己这里光追包正常

**Comment by dofes** [comment]
你是否对配置文件进行了修改,请自行关闭server.properties中的texturepack-required

**Comment by yufengya0420** [comment]
> 你是否对配置文件进行了修改? 请自行关闭server.properties中的texturepack-required

可以了，我以为和dll版的用法一样，改成false就能用了

**Comment by dofes** [comment]
>
